# Generated by Django 5.2.17 on 2026-09-16 02:56

import apps.moderation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderationcase_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='verification',
            name='document',
            field=models.FileField(upload_to='verification_documents/', validators=[apps.moderation.validators.validate_file_size]),
        ),
    ]
