# Generated by Django 5.2.17 on 2026-09-16 02:56

import apps.moderation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_seed_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='portfolio/', validators=[apps.moderation.validators.validate_file_size]),
        ),
    ]
