# Generated by Django 5.2.17 on 2026-09-16 02:01

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('professionals', '0003_seed_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('positions_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_start', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('location_label', models.CharField(blank=True, max_length=150)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('interest_window', models.CharField(choices=[('2h', '2 horas'), ('5h', '5 horas'), ('24h', '24 horas'), ('3d', '3 dias')], max_length=4)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Recebendo interessados'), ('partially_filled', 'Parcialmente preenchido'), ('filled', 'Preenchido'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='open', max_length=20)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='professionals.servicecategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='clients.clientprofile')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('applied', 'Interesse enviado'), ('shortlisted', 'Em consideração'), ('selected', 'Selecionado'), ('not_selected', 'Não selecionado'), ('withdrawn', 'Retirado'), ('expired', 'Expirado')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='professionals.professionalprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='requests.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('service_request', 'professional'), name='unique_interest_per_request')],
            },
        ),
    ]
