// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAccountActionToken = `-- name: ConsumeAccountActionToken :one
UPDATE account_action_tokens
SET used_at = now()
WHERE token_hash = $1
  AND purpose = $2
  AND used_at IS NULL
  AND expires_at > now()
RETURNING user_id
`

type ConsumeAccountActionTokenParams struct {
	TokenHash []byte `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

func (q *Queries) ConsumeAccountActionToken(ctx context.Context, arg ConsumeAccountActionTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAccountActionToken, arg.TokenHash, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createAccountActionToken = `-- name: CreateAccountActionToken :exec
INSERT INTO account_action_tokens (user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAccountActionTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Purpose   string             `json:"purpose"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAccountActionToken(ctx context.Context, arg CreateAccountActionTokenParams) error {
	_, err := q.db.Exec(ctx, createAccountActionToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, email_verified_at, status, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, email_verified_at, status, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, email_verified_at, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :one
SELECT
    EXISTS(
        SELECT 1 FROM professional_profiles
        WHERE professional_profiles.user_id = $1
    )::boolean AS is_professional,
    EXISTS(
        SELECT 1 FROM client_profiles
        WHERE client_profiles.user_id = $1
    )::boolean AS is_client
`

type GetUserRolesRow struct {
	IsProfessional bool `json:"is_professional"`
	IsClient       bool `json:"is_client"`
}

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) (GetUserRolesRow, error) {
	row := q.db.QueryRow(ctx, getUserRoles, userID)
	var i GetUserRolesRow
	err := row.Scan(&i.IsProfessional, &i.IsClient)
	return i, err
}

const invalidateAccountActionTokens = `-- name: InvalidateAccountActionTokens :exec
UPDATE account_action_tokens
SET used_at = now()
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidateAccountActionTokensParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Purpose string    `json:"purpose"`
}

func (q *Queries) InvalidateAccountActionTokens(ctx context.Context, arg InvalidateAccountActionTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateAccountActionTokens, arg.UserID, arg.Purpose)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, now()), updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, email, password_hash, display_name, email_verified_at, status, created_at, updated_at
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, now())
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1 AND status = 'active'
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
