// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (actor_id, action, resource, resource_id, metadata, ip_address, user_agent)
VALUES (
    $1, $2, $3, $4,
    $5, NULLIF($6, '')::inet, $7
)
RETURNING id, actor_id, action, resource, resource_id, metadata, ip_address, user_agent, created_at
`

type CreateAuditEventParams struct {
	ActorID    *uuid.UUID  `json:"actor_id"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID *uuid.UUID  `json:"resource_id"`
	Metadata   []byte      `json:"metadata"`
	IpAddress  interface{} `json:"ip_address"`
	UserAgent  string      `json:"user_agent"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
