// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getActiveCategory = `-- name: GetActiveCategory :one
SELECT id, slug, name, description
FROM service_categories
WHERE id = $1 AND is_active = true
`

type GetActiveCategoryRow struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) GetActiveCategory(ctx context.Context, id uuid.UUID) (GetActiveCategoryRow, error) {
	row := q.db.QueryRow(ctx, getActiveCategory, id)
	var i GetActiveCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, slug, name, description
FROM service_categories
WHERE is_active = true
ORDER BY name
`

type ListActiveCategoriesRow struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) ListActiveCategories(ctx context.Context) ([]ListActiveCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCategoriesRow
	for rows.Next() {
		var i ListActiveCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
