// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: professionals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProfessionalPortfolioItems = `-- name: CountProfessionalPortfolioItems :one
SELECT count(*)::integer
FROM portfolio_items i
JOIN professional_profiles p ON p.id = i.professional_profile_id
WHERE p.user_id = $1
`

func (q *Queries) CountProfessionalPortfolioItems(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProfessionalPortfolioItems, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSearchProfessionals = `-- name: CountSearchProfessionals :one
SELECT count(*)::bigint
FROM professional_profiles p
JOIN users u ON u.id = p.user_id AND u.status = 'active' AND u.email_verified_at IS NOT NULL
JOIN service_categories c ON c.id = p.primary_category_id AND c.is_active = true
WHERE p.primary_category_id = $1
  AND p.service_location IS NOT NULL
  AND (NOT $2::boolean OR p.available_now = true)
  AND ST_DWithin(
      p.service_location,
      ST_SetSRID(ST_MakePoint($3::double precision, $4::double precision), 4326)::geography,
      LEAST($5::integer, p.service_radius_km) * 1000
  )
`

type CountSearchProfessionalsParams struct {
	CategoryID       *uuid.UUID `json:"category_id"`
	AvailableNowOnly bool       `json:"available_now_only"`
	Longitude        float64    `json:"longitude"`
	Latitude         float64    `json:"latitude"`
	RadiusKm         int32      `json:"radius_km"`
}

func (q *Queries) CountSearchProfessionals(ctx context.Context, arg CountSearchProfessionalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProfessionals,
		arg.CategoryID,
		arg.AvailableNowOnly,
		arg.Longitude,
		arg.Latitude,
		arg.RadiusKm,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProfessionalAvailability = `-- name: CreateProfessionalAvailability :one
INSERT INTO availabilities (professional_profile_id, weekday, start_time, end_time)
SELECT id, $1, $2, $3
FROM professional_profiles
WHERE user_id = $4
RETURNING id, professional_profile_id, weekday, start_time, end_time, created_at
`

type CreateProfessionalAvailabilityParams struct {
	Weekday   int16       `json:"weekday"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) CreateProfessionalAvailability(ctx context.Context, arg CreateProfessionalAvailabilityParams) (Availability, error) {
	row := q.db.QueryRow(ctx, createProfessionalAvailability,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
	)
	var i Availability
	err := row.Scan(
		&i.ID,
		&i.ProfessionalProfileID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const createProfessionalPortfolioItem = `-- name: CreateProfessionalPortfolioItem :one
INSERT INTO portfolio_items (professional_profile_id, storage_key, original_name, media_type, size_bytes, sort_order)
SELECT id, $1, $2, $3, $4, $5
FROM professional_profiles
WHERE user_id = $6
RETURNING id, storage_key, original_name, media_type, size_bytes, sort_order, created_at
`

type CreateProfessionalPortfolioItemParams struct {
	StorageKey   string    `json:"storage_key"`
	OriginalName string    `json:"original_name"`
	MediaType    string    `json:"media_type"`
	SizeBytes    int64     `json:"size_bytes"`
	SortOrder    int16     `json:"sort_order"`
	UserID       uuid.UUID `json:"user_id"`
}

type CreateProfessionalPortfolioItemRow struct {
	ID           uuid.UUID          `json:"id"`
	StorageKey   string             `json:"storage_key"`
	OriginalName string             `json:"original_name"`
	MediaType    string             `json:"media_type"`
	SizeBytes    int64              `json:"size_bytes"`
	SortOrder    int16              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProfessionalPortfolioItem(ctx context.Context, arg CreateProfessionalPortfolioItemParams) (CreateProfessionalPortfolioItemRow, error) {
	row := q.db.QueryRow(ctx, createProfessionalPortfolioItem,
		arg.StorageKey,
		arg.OriginalName,
		arg.MediaType,
		arg.SizeBytes,
		arg.SortOrder,
		arg.UserID,
	)
	var i CreateProfessionalPortfolioItemRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.OriginalName,
		&i.MediaType,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfessionalAvailabilities = `-- name: DeleteProfessionalAvailabilities :exec
DELETE FROM availabilities
WHERE professional_profile_id = (SELECT id FROM professional_profiles WHERE user_id = $1)
`

func (q *Queries) DeleteProfessionalAvailabilities(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfessionalAvailabilities, userID)
	return err
}

const deleteProfessionalPortfolioItem = `-- name: DeleteProfessionalPortfolioItem :one
DELETE FROM portfolio_items i
USING professional_profiles p
WHERE i.id = $1
  AND i.professional_profile_id = p.id
  AND p.user_id = $2
RETURNING i.storage_key
`

type DeleteProfessionalPortfolioItemParams struct {
	ItemID uuid.UUID `json:"item_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProfessionalPortfolioItem(ctx context.Context, arg DeleteProfessionalPortfolioItemParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteProfessionalPortfolioItem, arg.ItemID, arg.UserID)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const getProfessionalProfileView = `-- name: GetProfessionalProfileView :one
SELECT
    p.id,
    p.user_id,
    p.bio,
    p.primary_category_id,
    c.slug AS category_slug,
    c.name AS category_name,
    p.skills,
    p.service_region,
    (p.service_location IS NOT NULL)::boolean AS location_configured,
    p.service_radius_km,
    p.reference_price_cents,
    p.available_now,
    p.availability_timezone,
    p.updated_at
FROM professional_profiles p
LEFT JOIN service_categories c ON c.id = p.primary_category_id
WHERE p.user_id = $1
`

type GetProfessionalProfileViewRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Bio                  string             `json:"bio"`
	PrimaryCategoryID    *uuid.UUID         `json:"primary_category_id"`
	CategorySlug         *string            `json:"category_slug"`
	CategoryName         *string            `json:"category_name"`
	Skills               []string           `json:"skills"`
	ServiceRegion        string             `json:"service_region"`
	LocationConfigured   bool               `json:"location_configured"`
	ServiceRadiusKm      int32              `json:"service_radius_km"`
	ReferencePriceCents  *int64             `json:"reference_price_cents"`
	AvailableNow         bool               `json:"available_now"`
	AvailabilityTimezone string             `json:"availability_timezone"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfessionalProfileView(ctx context.Context, userID uuid.UUID) (GetProfessionalProfileViewRow, error) {
	row := q.db.QueryRow(ctx, getProfessionalProfileView, userID)
	var i GetProfessionalProfileViewRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.PrimaryCategoryID,
		&i.CategorySlug,
		&i.CategoryName,
		&i.Skills,
		&i.ServiceRegion,
		&i.LocationConfigured,
		&i.ServiceRadiusKm,
		&i.ReferencePriceCents,
		&i.AvailableNow,
		&i.AvailabilityTimezone,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfessionalAvailabilities = `-- name: ListProfessionalAvailabilities :many
SELECT a.id, a.weekday, a.start_time, a.end_time
FROM availabilities a
JOIN professional_profiles p ON p.id = a.professional_profile_id
WHERE p.user_id = $1
ORDER BY a.weekday, a.start_time
`

type ListProfessionalAvailabilitiesRow struct {
	ID        uuid.UUID   `json:"id"`
	Weekday   int16       `json:"weekday"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) ListProfessionalAvailabilities(ctx context.Context, userID uuid.UUID) ([]ListProfessionalAvailabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listProfessionalAvailabilities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfessionalAvailabilitiesRow
	for rows.Next() {
		var i ListProfessionalAvailabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfessionalPortfolioItems = `-- name: ListProfessionalPortfolioItems :many
SELECT i.id, i.storage_key, i.original_name, i.media_type, i.size_bytes, i.sort_order, i.created_at
FROM portfolio_items i
JOIN professional_profiles p ON p.id = i.professional_profile_id
WHERE p.user_id = $1
ORDER BY i.sort_order, i.created_at
`

type ListProfessionalPortfolioItemsRow struct {
	ID           uuid.UUID          `json:"id"`
	StorageKey   string             `json:"storage_key"`
	OriginalName string             `json:"original_name"`
	MediaType    string             `json:"media_type"`
	SizeBytes    int64              `json:"size_bytes"`
	SortOrder    int16              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListProfessionalPortfolioItems(ctx context.Context, userID uuid.UUID) ([]ListProfessionalPortfolioItemsRow, error) {
	rows, err := q.db.Query(ctx, listProfessionalPortfolioItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfessionalPortfolioItemsRow
	for rows.Next() {
		var i ListProfessionalPortfolioItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.OriginalName,
			&i.MediaType,
			&i.SizeBytes,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProfessionalProfile = `-- name: LockProfessionalProfile :one
SELECT id
FROM professional_profiles
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockProfessionalProfile(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockProfessionalProfile, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const searchProfessionals = `-- name: SearchProfessionals :many
SELECT
    p.id,
    u.display_name,
    p.bio,
    c.id AS category_id,
    c.slug AS category_slug,
    c.name AS category_name,
    p.skills,
    p.service_region,
    p.service_radius_km,
    p.reference_price_cents,
    p.available_now,
    round((ST_Distance(
        p.service_location,
        ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography
    ) / 1000)::numeric, 1)::double precision AS distance_km,
    CAST(COALESCE((
        SELECT i.storage_key
        FROM portfolio_items i
        WHERE i.professional_profile_id = p.id
        ORDER BY i.sort_order, i.created_at
        LIMIT 1
    ), '') AS text) AS cover_storage_key
FROM professional_profiles p
JOIN users u ON u.id = p.user_id AND u.status = 'active' AND u.email_verified_at IS NOT NULL
JOIN service_categories c ON c.id = p.primary_category_id AND c.is_active = true
WHERE p.primary_category_id = $3
  AND p.service_location IS NOT NULL
  AND (NOT $4::boolean OR p.available_now = true)
  AND ST_DWithin(
      p.service_location,
      ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography,
      LEAST($5::integer, p.service_radius_km) * 1000
  )
ORDER BY distance_km, p.updated_at DESC, p.id
LIMIT $7::integer
OFFSET $6::integer
`

type SearchProfessionalsParams struct {
	Longitude        float64    `json:"longitude"`
	Latitude         float64    `json:"latitude"`
	CategoryID       *uuid.UUID `json:"category_id"`
	AvailableNowOnly bool       `json:"available_now_only"`
	RadiusKm         int32      `json:"radius_km"`
	PageOffset       int32      `json:"page_offset"`
	PageSize         int32      `json:"page_size"`
}

type SearchProfessionalsRow struct {
	ID                  uuid.UUID `json:"id"`
	DisplayName         string    `json:"display_name"`
	Bio                 string    `json:"bio"`
	CategoryID          uuid.UUID `json:"category_id"`
	CategorySlug        string    `json:"category_slug"`
	CategoryName        string    `json:"category_name"`
	Skills              []string  `json:"skills"`
	ServiceRegion       string    `json:"service_region"`
	ServiceRadiusKm     int32     `json:"service_radius_km"`
	ReferencePriceCents *int64    `json:"reference_price_cents"`
	AvailableNow        bool      `json:"available_now"`
	DistanceKm          float64   `json:"distance_km"`
	CoverStorageKey     string    `json:"cover_storage_key"`
}

func (q *Queries) SearchProfessionals(ctx context.Context, arg SearchProfessionalsParams) ([]SearchProfessionalsRow, error) {
	rows, err := q.db.Query(ctx, searchProfessionals,
		arg.Longitude,
		arg.Latitude,
		arg.CategoryID,
		arg.AvailableNowOnly,
		arg.RadiusKm,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProfessionalsRow
	for rows.Next() {
		var i SearchProfessionalsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Bio,
			&i.CategoryID,
			&i.CategorySlug,
			&i.CategoryName,
			&i.Skills,
			&i.ServiceRegion,
			&i.ServiceRadiusKm,
			&i.ReferencePriceCents,
			&i.AvailableNow,
			&i.DistanceKm,
			&i.CoverStorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfessionalProfile = `-- name: UpdateProfessionalProfile :exec
UPDATE professional_profiles
SET
    bio = $1,
    primary_category_id = $2,
    skills = $3,
    service_region = $4,
    service_location = CASE
        WHEN $5::double precision IS NULL OR $6::double precision IS NULL
            THEN service_location
        ELSE ST_SetSRID(ST_MakePoint($6::double precision, $5::double precision), 4326)::geography
    END,
    service_radius_km = $7,
    reference_price_cents = $8,
    available_now = $9,
    availability_timezone = $10,
    updated_at = now()
WHERE user_id = $11
`

type UpdateProfessionalProfileParams struct {
	Bio                  string     `json:"bio"`
	PrimaryCategoryID    *uuid.UUID `json:"primary_category_id"`
	Skills               []string   `json:"skills"`
	ServiceRegion        string     `json:"service_region"`
	Latitude             *float64   `json:"latitude"`
	Longitude            *float64   `json:"longitude"`
	ServiceRadiusKm      int32      `json:"service_radius_km"`
	ReferencePriceCents  *int64     `json:"reference_price_cents"`
	AvailableNow         bool       `json:"available_now"`
	AvailabilityTimezone string     `json:"availability_timezone"`
	UserID               uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateProfessionalProfile(ctx context.Context, arg UpdateProfessionalProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfessionalProfile,
		arg.Bio,
		arg.PrimaryCategoryID,
		arg.Skills,
		arg.ServiceRegion,
		arg.Latitude,
		arg.Longitude,
		arg.ServiceRadiusKm,
		arg.ReferencePriceCents,
		arg.AvailableNow,
		arg.AvailabilityTimezone,
		arg.UserID,
	)
	return err
}
