// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createClientProfile = `-- name: CreateClientProfile :one
INSERT INTO client_profiles (user_id, company_name)
VALUES ($1, $2)
RETURNING id, user_id, company_name, created_at, updated_at
`

type CreateClientProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CompanyName string    `json:"company_name"`
}

func (q *Queries) CreateClientProfile(ctx context.Context, arg CreateClientProfileParams) (ClientProfile, error) {
	row := q.db.QueryRow(ctx, createClientProfile, arg.UserID, arg.CompanyName)
	var i ClientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfessionalProfile = `-- name: CreateProfessionalProfile :one
INSERT INTO professional_profiles (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at, bio, primary_category_id, skills, service_region, service_location, service_radius_km, reference_price_cents, available_now, availability_timezone
`

func (q *Queries) CreateProfessionalProfile(ctx context.Context, userID uuid.UUID) (ProfessionalProfile, error) {
	row := q.db.QueryRow(ctx, createProfessionalProfile, userID)
	var i ProfessionalProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.PrimaryCategoryID,
		&i.Skills,
		&i.ServiceRegion,
		&i.ServiceLocation,
		&i.ServiceRadiusKm,
		&i.ReferencePriceCents,
		&i.AvailableNow,
		&i.AvailabilityTimezone,
	)
	return i, err
}

const getClientProfileByUserID = `-- name: GetClientProfileByUserID :one
SELECT id, user_id, company_name, created_at, updated_at FROM client_profiles WHERE user_id = $1
`

func (q *Queries) GetClientProfileByUserID(ctx context.Context, userID uuid.UUID) (ClientProfile, error) {
	row := q.db.QueryRow(ctx, getClientProfileByUserID, userID)
	var i ClientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfessionalProfileByUserID = `-- name: GetProfessionalProfileByUserID :one
SELECT id, user_id, created_at, updated_at, bio, primary_category_id, skills, service_region, service_location, service_radius_km, reference_price_cents, available_now, availability_timezone FROM professional_profiles WHERE user_id = $1
`

func (q *Queries) GetProfessionalProfileByUserID(ctx context.Context, userID uuid.UUID) (ProfessionalProfile, error) {
	row := q.db.QueryRow(ctx, getProfessionalProfileByUserID, userID)
	var i ProfessionalProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.PrimaryCategoryID,
		&i.Skills,
		&i.ServiceRegion,
		&i.ServiceLocation,
		&i.ServiceRadiusKm,
		&i.ReferencePriceCents,
		&i.AvailableNow,
		&i.AvailabilityTimezone,
	)
	return i, err
}
