# Generated by Django 5.2.17 on 2026-09-16 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('professionals', '0003_seed_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='clients.clientprofile')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('client', 'professional'), name='unique_favorite')],
            },
        ),
    ]
