# Generated by Django 5.2.17 on 2026-09-16 02:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_confirmed', models.BooleanField(blank=True, null=True)),
                ('professional_confirmed', models.BooleanField(blank=True, null=True)),
                ('client_responded_at', models.DateTimeField(blank=True, null=True)),
                ('professional_responded_at', models.DateTimeField(blank=True, null=True)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='requests.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contested', models.BooleanField(default=False)),
                ('contest_reason', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.serviceconfirmation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('confirmation', 'author'), name='unique_review_per_author')],
            },
        ),
    ]
